spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emart?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: C20041109
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

  redis:
    host: localhost
    database: 0
    port: 6379
    password: 123456
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

# Alipay配置
alipay:
  gateway: https://openapi.alipaydev.com/gateway.do  # 沙箱网关
  app-id: 9021000158686121
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCuLu5CmvpUxYRsJC3HG8Q6hCoRK4TWy3fDWuz3LUJjLno7PWRRtFaPTKb2dz47M/jOkyZlUibkc/251nG9tiV2qFn9m+bwACzW8ViFrWx1Hyg0iDVjK6ZQukzKEjnda3vgNvOoBSvKlajhDxVUThx6PR4v5/E3zc7pJ4X6D27RIQ7Wi26o7iay0uaj1un/rlgfCJB+j++nPPu1xDQZcdQehB/mS/IItX1eo+9bnJ+Kl2dmZzeGIkB1xJTgG4aEmadE0Q2KgzrTVtqBfyNk9smBY86RJ3PB9L1epKjHhgI1SqXp6URDkQAyvJJbcGRY4oQPCZ57LUJ9jBD8vLEUcVq1AgMBAAECggEAQcsiXnBRzIGLQpnr3MDFP2E6zp+EnuneRCFtTvR+lh4xN306Do6y/4/xpTlnfU9lVQpKP41neXXCylaRQhqyTf7LdztTYSZ/yXUCfgQC6r6pHiaxG9OaD/Y/GTkHOHboJMo9ASNq5ivfzZs38E9M/HNnmqre97g6xuER/2Gi90UH/pDmYKI5f1UIc0tLQWSZ7QnlmkwnH0cWl5PJfUk9dwQm/0JkwGik227nv2H0wSMl6Xiz/68TFZSh0fNEhr2/X56RPAhhMFPC8xUyHGbJ4wI1WDujyQUm1ha8039IVRC/hqIeWaP4CaahVy+xO4WQa7paiG2wUMaOcRi7t/FegQKBgQDqpEOlmua3ChdeuBUP5B5dXklJNqeciK0xe0OfQKAB/YpKpOwxpywXT+4rSNVO55+WzcHzwMMSyaKjxliXgFQkgD3wilXsDP33qtWmt7ikwn9xtKrrbnE3MpOFy13AnTBaTbV/zJo+UJo/wtfEsNu+8MindBBYZsFzUj8CeypOYQKBgQC+CdYlGPwR1jAHSBO6pGaMfKQS9kaFCFimuEUQ+S4z31/XBPyj0fwCUHvCam9UU9ZJpUljKc5hnDW4fHAK+CDBqP6yIISzO9CoHJQRbkkiJu9x7Ao9YtHR5jnUquTSc73hBJoNyY6SVneg5G3OYFej0Ocgglk1BIJhHFOgLQik1QKBgQDnmwaOw2xyRgq1WvynN+NlA/lQxBsD3sEds28XFaIa9Nl5PntJs5pI1IPhw72Raf3Ty/tjD+U9eTwJbnHp8Sic8tywvst6+YQB4GWNb5FZSAamBNAlHVmxQ0HsccVzp3Sf3k6F/D5Pvh3TTA7QvkXZnjBhYaX0rFDM9OTvHQWwYQKBgDGcdchHhn7NkMpF2ciu5Iqme1rr6isOq74Sew1cT+CA3w9OIPpPdl/QTQ7LJHc6T8X4HXmCz3sSAcBA1Cs47axBBwTPknUMF4Pbuhf216bPzVDLUz0FUEtgtBY96vC6AIb+4YzZ4pt3cVGScMwgwKBmiAAnp0w8+iCJ+ZbmSsxlAoGAff/uRDE0/TwCCU0XoGereAINlTQywkxNYdG0XHZQBVndx1TpDiAdBz3QeoC+SYeqiDGpzIbQ7qCuEwiLCpjafvEoaYMulDvaYF4wah/LoMqQNh9pqxcqTRoxFJwZPS1I00+WnJgvO5Yr1CZ/ybsZotHgWm6nFg89YIsBLVAFLbg=
    -----END PRIVATE KEY-----
  alipay-public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2yDl+rvFn/qnIAUk+5dlaPYXE9Ul6wPhJ9pG7j7yMueX1PMGYYtgUUUheNvWJl+hqH/YJ0l1AJELGxnSClkQlw51Z5um3ix+cvkVHTOGj+GAKg/ZrXyTsL5MvB98b8Zpj5Fm8qDuD++jpaSD2ADF6QgvEJWRmQ4tm20CPU6bepSZi2z+hN8L/ijQCkOjihaxTKm27z58t8cS4ZOUfnBELU+Jkg1a4a3YmRV2/QdBZHvd3f1u30RcUUOlUnhqvlYgSHqovFUbDX6prC2rkj3MdyzdqCrzAg+ssbyMd56XbNnzlSi6pm5Dgw6InQoySKC/lzgju/s1vcrEeyZON4+jhQIDAQAB
    -----END PUBLIC KEY-----
  return-url: http://localhost:5174/payment/return
  notify-url: http://localhost:8080/payment/notify
  sign-type: RSA2

# 日志配置
logging:
  level:
    root: info
    com.emart: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
